### ISSUE TITLE
Version on API and API example pages not shown correctly

### ISSUE THREAD

**Issue by touwwouter** [cmbi/xssp-api#73] opened 2015-04-16 11:34 UTC
The version footer for the xssp version (#56) is also visible on the API and API example pages, without version number (bug). On the latter it overlaps with the code example (enhancement?).

**Comment by cbaakman** [comment] 2017-06-06 11:41
It doesn't seem to overlap anymore. However, it's still there.

**Comment by touwwouter** [comment] 2017-06-07 10:38
So, fixed?

**Comment by cbaakman** [comment] 2017-06-08 07:46
The version number will be added in #91. Once this is merged, the issue is fully fixed.

**Closed** 2017-06-08 07:57 UTC
Labels: bug, enhancement
